// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceTracker.Infrastructure.Persistence;

#nullable disable

namespace PriceTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620175943_AddScraperTypeToStore")]
    partial class AddScraperTypeToStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceTracker.Domain.Entities.AttributeType", b =>
                {
                    b.Property<long>("AttributeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttributeTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AttributeTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_attribute_types_name");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.AttributeValue", b =>
                {
                    b.Property<long>("AttributeValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AttributeValueId"));

                    b.Property<long>("AttributeTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AttributeValueId");

                    b.HasIndex("AttributeTypeId")
                        .HasDatabaseName("idx_attribute_values_type");

                    b.HasIndex("AttributeTypeId", "Value")
                        .IsUnique()
                        .HasDatabaseName("idx_attribute_values_type_value");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_categories_name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Email");

                    b.Property<long>("PriceHistoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("TrackingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TriggeredPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("PriceHistoryId");

                    b.HasIndex("SentAt")
                        .IsDescending()
                        .HasDatabaseName("idx_notifications_sent_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_notifications_status");

                    b.HasIndex("TrackingId")
                        .HasDatabaseName("idx_notifications_tracking");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("PriceInUsd")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScrapedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasAlternateKey("ListingId", "RecordedAt");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("idx_price_history_currency");

                    b.HasIndex("RecordedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_price_history_recorded_at");

                    b.HasIndex("ListingId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_price_history_listing_time");

                    b.HasIndex("ListingId", "ScrapedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_price_history_listing_scrape");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("ProductId");

                    b.HasIndex("Brand")
                        .HasDatabaseName("idx_products_brand");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_products_category");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_products_name_fts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ProductImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_product_images_product");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("VariantId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_product_variants_active");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_product_variants_product");

                    b.HasIndex("Sku")
                        .HasDatabaseName("idx_product_variants_sku");

                    b.HasIndex("ProductId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("idx_product_variants_product_sku")
                        .HasFilter("\"Sku\" IS NOT NULL");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ScrapeLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemsScraped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("idx_scrape_logs_listing");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_scrape_logs_started");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_scrape_logs_status");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("idx_scrape_logs_store");

                    b.ToTable("ScrapeLogs");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ScraperType")
                        .HasColumnType("integer");

                    b.HasKey("StoreId");

                    b.HasIndex("Country")
                        .HasDatabaseName("idx_stores_country");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("idx_stores_currency_code");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.StoreProductListing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_listings_active");

                    b.HasIndex("LastScrapedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_listings_scraped_at");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_listings_product");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("idx_listings_store");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_listings_variant");

                    b.HasIndex("VariantId", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("idx_listings_variant_store");

                    b.ToTable("StoreProductListings");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.UserProductTracking", b =>
                {
                    b.Property<Guid>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotifyEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackingId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_tracking_active");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("idx_tracking_listing");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_tracking_product");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tracking_user");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_tracking_variant");

                    b.HasIndex("UserId", "ProductId", "VariantId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("idx_tracking_unique");

                    b.ToTable("UserProductTrackings");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.VariantAttribute", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.Property<long>("AttributeValueId")
                        .HasColumnType("bigint");

                    b.HasKey("VariantId", "AttributeValueId");

                    b.HasIndex("AttributeValueId")
                        .HasDatabaseName("idx_variant_attributes_value");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_variant_attributes_variant");

                    b.ToTable("VariantAttributes");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.AttributeValue", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.AttributeType", "AttributeType")
                        .WithMany("Values")
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeType");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.PriceHistory", "PriceHistory")
                        .WithMany("Notifications")
                        .HasForeignKey("PriceHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.UserProductTracking", "Tracking")
                        .WithMany("Notifications")
                        .HasForeignKey("TrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PriceHistory");

                    b.Navigation("Tracking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Currency", "Currency")
                        .WithMany("PriceHistories")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.StoreProductListing", "Listing")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Product", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ScrapeLog", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.StoreProductListing", "Listing")
                        .WithMany("ScrapeLogs")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriceTracker.Domain.Entities.Store", "Store")
                        .WithMany("ScrapeLogs")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Store", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Currency", "Currency")
                        .WithMany("Stores")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.StoreProductListing", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Product", "Product")
                        .WithMany("Listings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.Store", "Store")
                        .WithMany("Listings")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.ProductVariant", "Variant")
                        .WithMany("Listings")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.UserProductTracking", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.Currency", "Currency")
                        .WithMany("Trackings")
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.StoreProductListing", "Listing")
                        .WithMany("Trackings")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PriceTracker.Domain.Entities.Product", "Product")
                        .WithMany("Trackings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.User", "User")
                        .WithMany("Trackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.ProductVariant", "Variant")
                        .WithMany("Trackings")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Currency");

                    b.Navigation("Listing");

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.VariantAttribute", b =>
                {
                    b.HasOne("PriceTracker.Domain.Entities.AttributeValue", "AttributeValue")
                        .WithMany("VariantAttributes")
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceTracker.Domain.Entities.ProductVariant", "Variant")
                        .WithMany("VariantAttributes")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.AttributeType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.AttributeValue", b =>
                {
                    b.Navigation("VariantAttributes");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Currency", b =>
                {
                    b.Navigation("PriceHistories");

                    b.Navigation("Stores");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.PriceHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Listings");

                    b.Navigation("Trackings");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Trackings");

                    b.Navigation("VariantAttributes");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.Store", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("ScrapeLogs");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.StoreProductListing", b =>
                {
                    b.Navigation("PriceHistories");

                    b.Navigation("ScrapeLogs");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("PriceTracker.Domain.Entities.UserProductTracking", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
