FROM node:20-alpine AS build
ARG VITE_API_URL=
WORKDIR /app

COPY ["frontend/package.json", "frontend/package-lock.json*", "./"]
RUN npm install
COPY frontend/ ./

ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist .
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
